backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'menu'
    label: 'Menu'
    folder: 'src/pages/menu'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'menu-group',
        }
      - { label: 'Menu Group', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'subtitle', widget: 'string' }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          default: 3,
          valueType: 'int',
          min: 1,
        }
      - label: 'Menu Subgroups'
        name: subgroups
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
            required: false
          - label: 'Menu Items'
            name: items
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Price
                name: price
                widget: string
              - label: Description
                name: description
                widget: text
                required: false

  - name: 'team'
    label: 'Team'
    folder: 'src/pages/team'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'team-member',
        }
      - { label: 'First Name', name: 'title', widget: 'string' }
      - { label: 'Last Name', name: 'lastname', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          default: 3,
          valueType: 'int',
          min: 1,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/press/index.md'
        label: 'Press'
        name: 'press'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'press-page',
            }
          - {
              label: Articles,
              name: articles,
              widget: list,
              fields:
                [
                  { label: Publication, name: publication, widget: string },
                  { label: title, name: title, widget: string },
                  {
                    label: Date Published,
                    name: date,
                    widget: date,
                    format: MMMM YYYY,
                  },
                  { label: Summary, name: summary, widget: text },
                  { label: Link, name: link, widget: string },
                ],
            }
      - file: 'src/pages/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Banner', name: 'banner', widget: 'string' }
