backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "menu"
    label: "Menu"
    folder: "src/pages/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "menu-group"}
      - {label: "Menu Group", name: "title", widget: "string"}
      - {label: "Time", name: "time", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 3, valueType: "int", min: 1}
      - label: "Menu Subgroups"
        name: subgroups
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: "Menu Items"
            name: items
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Price
                name: price
                widget: string
              - label: Description
                name: description
                widget: text
                required: false

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Blurbs
                name: blurbs
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Text
                    name: text
                    widget: text
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Blurbs
                name: blurbs
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Text
                    name: text
                    widget: text
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: string
              - label: Author
                name: author
                widget: string
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/press/index.md"
        label: "Press"
        name: "press"
        fields:
          - {label: Articles, name: articles, widget: list, fields: [{label: Publication, name: publication, widget: string}, {label: title, name: title, widget: string}, {label: Date Published, name: date, widget: date, format: MMMM YYYY}, {label: Summary, name: summary, widget: text}]}

  - name: "team"
    label: "Team"
    folder: "src/pages/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-member"}
      - {label: "First Name", name: "title", widget: "string"}
      - {label: "Last Name", name: "lastname", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 3, valueType: "int", min: 1}
      - {label: "Body", name: "body", widget: "markdown"}
